## Execute this two line when working with anaconda for automatically reload any new version of your code

In [1]:
%load_ext autoreload
%autoreload 2

## Required methods

In [2]:
def readFASTAs(fileName):

    '''
    :param fileName:
    :return: rna sequences
    '''
    with open(fileName, 'r') as file:
        v = []
        genome = ''
        for line in file:
            if line[0] != '>':
                genome += line.strip()
            else:
                v.append(genome.upper())
                genome = ''
        v.append(genome.upper())
        del v[0]
        return v

def readLabels(fileName):

    '''
    :param fileName:
    :return: label of rna sequences
    '''
    with open(fileName, 'r') as file:
        v = []
        i=0
        for line in file:
            if line != '\n':
                if i%2 == 0 and 'positive' in line.lower():
                    v.append('True')
                if i%2 == 0 and 'negative' in line.lower():
                    v.append('False')    
            i=i+1 
        return v



def fetchXY(fileName):
    # print('Please, enter the full path of FASTA file:')
    # X = readFASTA(input().strip())
    #
    # print('Please, enter the full path of label file:')
    # Y = readLabel(input().strip())
    #
    # from sklearn.preprocessing import LabelEncoder
    # Y = LabelEncoder().fit_transform(Y)
    #
    # assert len(X)==len(Y), 'Numbers of FASTA and numbers of type are not equal.'
    
    X = readFASTAs(fileName)
    Y = readLabels(fileName)

    
    from sklearn.preprocessing import LabelEncoder
    Y = LabelEncoder().fit_transform(Y)

    assert len(X)==len(Y), 'Numbers of sequence and number of labels are not equal.'

    return X, Y

## Step 1 : Reading Dataset

In [3]:
#import read
file_path= '../dataset/benchmark.txt'
X, Y = fetchXY(file_path)
print('\nDatasets fetching done.')
print('==================Details of X==============================')
print('Length of X:',len(X),'\nType:',type(X))
print(X[0])
print('==================Details of Y==============================')
print('Length of X:',len(Y),'\nType:',type(Y))
print(Y[0])




Datasets fetching done.
==================Details of X==============================
Length of X: 244 
Type: <class 'list'>
UAUGGUCGCAAAGGUUUUCUUUAUUACGUUGCAGACUUCAGAAAAAAGUCA
==================Details of Y==============================
Length of X: 244 
Type: <class 'numpy.ndarray'>
1


## Step 2: Feature Generation 

In [4]:
import generateFeatures

#Composition of 3-mers
pkTuple = 5
#Composition of 5-gapped 3-mers
#pkGap = 1
psequenceType='RNA'

#print(kmers('ABCD',3))
print('Features extraction begins. Be patient! The machine will take some time.')

T = generateFeatures.genFeatures(pkTuple,psequenceType, X, Y)

print(T)
X_train = T[:,:-1]
Y_train = T[:,-1]
print('Features extraction ends.')
print('[Total extracted feature: {}]\n'.format(X_train.shape[1]))
#print(X_train[0])
#print(X[0])
#x=X[0]

#A = x.count('A');
#C = x.count('C');
#G = x.count('G');
#U = x.count('U')
#print(len(X[1]),A,C,G,U)
        
#############################################################################


Features extraction begins. Be patient! The machine will take some time.
[[16.  8. 10. ...  0.  0.  1.]
 [18. 12.  6. ...  0.  0.  1.]
 [15. 20.  7. ...  0.  0.  1.]
 ...
 [20.  6. 12. ...  0.  0.  0.]
 [18. 12.  6. ...  0.  0.  0.]
 [15. 16.  4. ...  0.  0.  0.]]
Features extraction ends.
[Total extracted feature: 1375]



## Step 3 : Save Generated Features 

In [5]:
print('Converting (full) CSV is begin.')
import store
store.saveCSV(X_train, Y_train, 'full')
print('Converting (full) CSV is end.')

Converting (full) CSV is begin.
Converting (full) CSV is end.
